version: "3.4"

services:
  php:
    container_name: ${PHP_CONTAINER_NAME}
    build:
      context: ./api_001
      target: app_php
    depends_on:
      - ${POSGRES_CONTAINER_NAME}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php


  caddy:
    container_name: ${CADDY_CONTAINER_NAME}
    build:
      context: api_001/
      target: app_caddy
    depends_on:
      - php
    environment:
      # PWA_UPSTREAM: pwa:3000
      SERVER_NAME: ${SERVER_NAME}, caddy:80
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      # HTTP
      - target: 80
        published: ${CADDY_HTTP_PORT}
        protocol: ${CADDY_HTTP_PORT_PROTOCOL}
      # HTTPS
      - target: 443
        published: ${CADDY_HTTPS_PORT}
        protocol: ${CADDY_HTTPS_PORT_PROTOCOL}
      # HTTP/3
      - target: 443
        published: ${CADDY_HTTP3_PORT}
        protocol: ${CADDY_HTTP3_PORT_PROTOCOL}

  postgres:
    container_name: ${POSGRES_CONTAINER_NAME}
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./api/docker/db/data:/var/lib/postgresql/data

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  db_data: